image: node:18  

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

# Build stage
build:
  stage: build
  script:
    - yarn install          
    - yarn build            
  artifacts:
    paths:
      - dist                
    expire_in: 1 hour

test:
  stage: test
  script:
    - yarn test            
  cache:
    paths:
      - node_modules/
    policy: pull

# Deploy stage to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - build                
  script:
    - rm -rf public          
    - cp -r dist/* public/  
  artifacts:
    paths:
      - public              
  only:
    - 23-t004-hostSite       