image: node:23

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - corepack enable
  - yarn install --frozen-lockfile || yarn install --no-lockfile 

# Build stage
build:
  stage: build
  script:
    - yarn install --no-lockfile   
    - yarn build
    - ls -la 
  artifacts:
    paths:
      - build 
    expire_in: 1 hour

# Deploy to GitLab Pages
pages:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public   
    - cp -r dist/* public/  
  artifacts:
    paths:
      - public
  only:
    - 23-t004-hostSite