image: node:18  

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - yarn.lock

variables:
  YARN_NODE_LINKER: node-modules 

before_script:
  - corepack enable
  - yarn install

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - 23-t004-hostSite  