image: node:latest

stages:
  - build
  - deploy

cache:
  key: yarn-dependencies
  paths:
    - node_modules/
  policy: pull-push

  # Netlify CLI caching
  key: netlify-cache
  paths:
    - ~/.netlify
  policy: pull-push

before_script:
  - corepack enable
  - yarn install --frozen-lockfile || yarn install --no-lockfile 

# Build Stage
build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist 
    expire_in: 1 hour

# Deploy Stage (Netlify)
deploy_prod:
  stage: deploy
  dependencies:
    - build
  script:
    - npx netlify deploy --dir "dist" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - 23-t004-hostSite