image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/
    - ~/.netlify

before_script:
  - export NODE_ENV=production 
  - corepack enable
  - yarn install --frozen-lockfile --prefer-offline  
  - yarn global add typescript

build:
  stage: build
  script:
    - yarn build
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

deploy_prod:
  stage: deploy
  dependencies:
    - build
  script:
    - npx netlify deploy --dir "dist" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - 23-t004-hostSite