image: node:latest

stages:
  - deploy

cache:
  key: yarn-cache
  paths:
    - .yarn-cache/
  policy: pull-push

before_script:
  - corepack enable
  - rm -rf node_modules yarn.lock 
  - yarn config set cache-folder .yarn-cache
  - yarn install --frozen-lockfile --silent
  - npm install -g netlify-cli

deploy_prod:
  stage: deploy
  script:
    - yarn build
    - netlify deploy --dir "dist" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - test-u019