image: node:latest

stages:
  - deploy 

cache:
  key: yarn-dependencies
  paths:
    - node_modules/
  policy: pull-push

  # Netlify CLI caching
  key: netlify-cache
  paths:
    - ~/.netlify
  policy: pull-push

before_script:
  - corepack enable
  - yarn install --frozen-lockfile || yarn install --no-lockfile 
  - npm install -g netlify-cli 

deploy_prod:
  stage: deploy
  script:
    - yarn build
    - netlify deploy --dir "dist" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - 23-t004-hostSite