image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - corepack enable
  - yarn install --frozen-lockfile || yarn install --no-lockfile

deploy_prod:
  stage: deploy
  script:
    - echo "REACT_APP_BASE_URL=https://culturenet-apis.netlify.app/.netlify/functions/api" >> ".env"
    - echo "REACT_APP_SUPABASE_URL=$SUPABASE_DATABASE_URL" >> ".env"
    - echo "REACT_APP_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> ".env"
    - yarn build
    - cat .env  # Debugging: Ensure environment variables are set
    - npx netlify-cli deploy --dir "dist" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - 23-t004-hostSite