image: node:latest 

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - corepack enable
  - yarn install --frozen-lockfile || yarn install --no-lockfile 

# Build stage
build:
  stage: build
  script:
    - echo "VITE_SUPABASE_URL=$SUPABASE_URL" >> ".env"
    - echo "VITE_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> ".env"
    - yarn build
    - ls -la dist 
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

# Deploy stage
deploy_prod:
  stage: deploy
  script:
    - npm install -g netlify-cli  
    - netlify deploy --dir "dist" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - 23-t004-hostSite
  dependencies:
    - build