image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - corepack enable
  - yarn install --frozen-lockfile || yarn install --no-lockfile 

# Build stage
build:
  stage: build
  script:
    - echo "REACT_APP_BASE_URL=https://culturenet-apis.netlify.app/.netlify/functions/api" >> ".env"
    - echo "REACT_APP_SUPABASE_URL=$SUPABASE_URL" >> ".env"
    - echo "REACT_APP_SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> ".env"
    - yarn install --no-lockfile   
    - yarn build
    - ls -la dist  
  artifacts:
    paths:
      - dist
    expire_in: 1 hour

prepare_public:
  stage: deploy
  dependencies:
    - build
  script:
    - rm -rf public
    - mkdir public 
    - cp -r dist/. public/
    - ls -la public 
  artifacts:
    paths:
      - public

# Deploy to Netlify
deploy_prod:
  stage: deploy
  dependencies:
    - prepare_public
  script:
    - ls -la public  
    - npx netlify-cli deploy --dir "public" --auth $AUTH_TOKEN --site $SITE_ID_PROD --prod
  only:
    - 23-t004-hostSite